server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientservice
          uri: lb://clientservice
          predicates:
          - Path=/apiclient/**
        - id: productservice
          uri: lb://productservice
          predicates:
          - Path=/apicredit/**,/apiaccount/**,/apiprodreport/**
        - id: atmservice
          uri: lb://atmservice
          predicates:
          - Path=/apiatm/**
        - id: transactservice
          uri: lb://transactservice
          predicates:
          - Path=/apitransaction/**