server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientservice
          uri: lb://clientservice
          predicates:
            - Path=/apiclient/**
        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/product/**
 